# our base image
FROM tomcat:7-jre7

ENV JAVA_OPTS="-Xmx3072m -Xms1024m -XX:PermSize=256m -XX:MaxPermSize=512m -XX:NewSize=128m -Djava.awt.headless=true -Djava.awt.headlesslib=true"
RUN rm -rf /usr/local/tomcat/webapps/*
ADD web/openmrs.war /usr/local/tomcat/webapps/openmrs.war
ADD web/openmrs-runtime.properties /root/.OpenMRS/openmrs-runtime.properties
ADD web/modules/*.omod /root/.OpenMRS/modules/

# Open Ports


