# our base image
FROM mysql:5.6

ENV MYSQL_ROOT_PASSWORD=nuride123!
ENV MYSQL_DATABASE=openmrs
ENV MYSQL_USER=openmrs
ENV MYSQL_PASSWORD=openmrs    

COPY db/*.sql /docker-entrypoint-initdb.d/

VOLUME /var/lib/mysql
